# Build configuration
targets:
  $default:
    builders:
      freezed:freezed:
        enabled: true
        generate_for:
          - lib/**/*.dart
      json_serializable:json_serializable:
        enabled: true
        generate_for:
          - lib/**/*.dart
      # Temporarily disable retrofit_generator due to version conflict
      # retrofit_generator:retrofit_generator:
      #   enabled: false
