include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    non_abstract_class_inherits_abstract_member: ignore
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: false
